pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/baseami/upgrade/foundation_ami/upgrade_check.py'
                sh 'python sources/baseami/upgrade/foundation_ami/upgrade_check.py'
            }
        }
    }
}
