pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'pip install --upgrade pip'
		sh 'pip install requests'
		sh 'sudo apt-get install git'
                sh 'python sources/baseami/upgrade/foundation_ami/upgrade_check.py u14'
                sh 'git add .'
                sh 'git commit -m \'update json file\''
            }
        }
    }
}
